tasks:
  - init: |
      ./scripts/gen_word_list.sh
      python -m http.server 8080 &

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - esbenp.prettier-vscode

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
