tasks:
  - init: |
      ./scripts/gen_word_list.sh
      python -m http.server 8080 &
      git update-index --assume-unchanged words.txt

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - esbenp.prettier-vscode
