name: CI
on: [push]
jobs:
  test-game-logic:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run node -v
        run: node -v
      - name: Run npm install
        run: npm install
      - name: Run test
        run: npm run test-ci
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ./results/unit-test-results.xml
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install mkcert
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      - name: Generate self-signed certificate
        run: |
          mkcert -install
          mkdir ssl
          cd ssl
          mkcert localhost 127.0.0.1 ::1
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          start: npm run devs
          wait-on: 'https://localhost:5501'
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: ./results/cypress-test-results-*.xml
  publish-test-results:
    needs: [test-game-logic, cypress-run]
    runs-on: ubuntu-latest
    steps:
      - name: Download test results artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./results
          pattern: "*-test-results"
          merge-multiple: true
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./results/*-test-results*.xml
